### ISSUE TITLE
what is your idea?

### ISSUE THREAD

**Issue by monib110** [OwEnXiaoMing/Louvain-method-Methode-de-Louvain-#1]
Hello.
What is your idea for improve Louvain algorithm?
Could you please share with me?

**Comment by OwXiaoM** [comment]
Well it is just because my prof let me make a little program by Louvain Method, however I could't find a repo in github which is simple enough, so I write a code by myself, without referring any other code.

**Comment by monib110** [comment]
Thanks for your reply.. So it is an implementation of Louvain, without any improvements? Sent from Mail for Windows From: XIAOMING ZHANGSent: Wednesday, June 15, 2022 4:33 PMTo: OwEnXiaoMing/Louvain-method-Methode-de-Louvain-Cc: mohadese; AuthorSubject: Re: [OwEnXiaoMing/Louvain-method-Methode-de-Louvain-] what is your idea? (Issue #1) Well it is just because my prof let me make a little program by Louvain Method, however I could't find a repo in github which is simple enough, so I write a code by myself, without referring any other code.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by OwXiaoM** [comment]
Yes it is the vanilla Louvain Method with a visilisation.

**Comment by monib110** [comment]
Thank you. Sent from Mail for Windows From: XIAOMING ZHANGSent: Wednesday, June 15, 2022 6:28 PMTo: OwEnXiaoMing/Louvain-method-Methode-de-Louvain-Cc: mohadese; AuthorSubject: Re: [OwEnXiaoMing/Louvain-method-Methode-de-Louvain-] what is your idea? (Issue #1) Yes it is the vanilla Louvain Method with a visilisation.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>
